import { expect, test } from '@playwright/test'

test('手机首页只显示指定的学习内容', async ({ page }) => {
  const pageErrors: string[] = []
  page.on('pageerror', (error) => pageErrors.push(error.message))
  await page.goto('/')

  await expect(page.getByRole('button', { name: '搜索' })).toBeVisible()
  await expect(page.getByRole('button', { name: '消息提示' })).toBeVisible()
  await expect(page.getByRole('button', { name: '主题设置' })).toHaveCount(0)
  await expect(page.getByText('字体一')).toBeVisible()
  await expect(page.getByText('字体二')).toBeVisible()
  await expect(page.getByText('今日计划')).toBeVisible()
  await expect(page.getByRole('button', { name: '修改' })).toBeVisible()
  await expect(page.getByText('已新学')).toBeVisible()
  await expect(page.getByText('已复习')).toBeVisible()
  await expect(page.getByText('已学习时长')).toBeVisible()
  await expect(page.getByText('x/y')).toHaveCount(2)
  await expect(page.getByText('xxx min')).toBeVisible()
  await expect(page.getByRole('button', { name: '学习', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '复习', exact: true })).toBeVisible()
  await expect(page.getByText('功能切换')).toHaveCount(0)
  const navigationItems = page.locator('.navigation-item')
  await expect(navigationItems).toHaveCount(4)
  const hasStackedNavigationContent = await page.locator('.navigation-content').evaluateAll((items) => (
    items.every((item) => {
      const icon = item.querySelector('.van-icon')
      const label = item.querySelector('.navigation-label')
      if (!icon || !label) return false
      return icon.getBoundingClientRect().bottom <= label.getBoundingClientRect().top
    })
  ))
  expect(hasStackedNavigationContent).toBe(true)
  await expect(page.getByText('单字练习')).toBeVisible()
  await expect(page.getByText('对照阅读')).toBeVisible()
  await expect(page.getByText('我', { exact: true })).toBeVisible()
  await expect(page.getByText('今天要做的事')).toHaveCount(0)
  await page.screenshot({ path: 'artifacts/home-mobile.png', fullPage: true })

  await page.getByRole('button', { name: '修改' }).click()
  await expect(page.getByText('修改计划', { exact: true })).toBeVisible()
  await expect(page.getByRole('tab', { name: '修改字体' })).toBeVisible()
  await expect(page.getByText('学习字体：字体一')).toBeVisible()
  await expect(page.getByText('选择学习模式（支持多选）')).toBeVisible()
  await page.getByRole('button', { name: '返回' }).click()
  await expect(page.getByText('今日计划')).toBeVisible()
  await page.getByRole('button', { name: '修改' }).click()
  await expect(page.getByText('修改计划', { exact: true })).toBeVisible()
  await expect(page.locator('.plan-wheel')).toBeVisible()
  await expect(page.locator('uni-picker-view')).toHaveCount(0)
  await expect(page.locator('uni-radio')).toHaveCount(0)
  const wheel = page.locator('.plan-wheel')
  await expect(wheel).toHaveAttribute('data-selected-count', '15')
  await wheel.hover()
  await page.mouse.wheel(0, 80)
  await expect(wheel).toHaveAttribute('data-selected-count', '20')
  await page.mouse.wheel(0, 10000)
  await expect(wheel).toHaveAttribute('data-selected-count', '100')
  await page.waitForTimeout(300)
  const firstMode = page.locator('.mode-card').filter({ hasText: '查看学习字体选择对照字体' })
  const secondMode = page.locator('.mode-card').filter({ hasText: '查看对照字体选择学习字体' })
  await firstMode.click()
  await secondMode.click()
  await expect(firstMode.locator('.uni-checkbox-input svg')).toHaveCount(1)
  await expect(secondMode.locator('.uni-checkbox-input svg')).toHaveCount(1)
  await page.screenshot({ path: 'artifacts/plan-mobile.png', fullPage: true })
  await page.getByRole('button', { name: '保存计划' }).click()
  await expect(page.getByText('今日计划')).toBeVisible()
  expect(pageErrors).toEqual([])
})

test('修改字体页可切换当前字体且不显示徽章入口', async ({ page }) => {
  const consoleErrors: string[] = []
  page.on('pageerror', (error) => consoleErrors.push(error.message))
  page.on('console', (message) => {
    if (message.type() === 'error') consoleErrors.push(message.text())
  })
  await page.goto('/#/pages/plan/index')

  await page.getByRole('tab', { name: '修改字体' }).click()
  await expect(page.getByText('字体一', { exact: true })).toBeVisible()
  await expect(page.getByText('字体二', { exact: true })).toBeVisible()
  await expect(page.getByText('当前在学')).toBeVisible()
  await expect(page.getByRole('button', { name: '添加字体' })).toBeVisible()
  await expect(page.getByText('徽章', { exact: true })).toHaveCount(0)
  await page.screenshot({ path: 'artifacts/fonts-mobile.png', fullPage: true })

  await page.getByRole('button', { name: '选择字体二' }).click()
  await expect(page.getByRole('button', { name: '选择字体二' }).getByText('当前在学')).toBeVisible()
  await page.getByRole('tab', { name: '修改计划' }).click()
  await expect(page.getByText('学习字体：字体二')).toBeVisible()
  await page.getByRole('tab', { name: '修改字体' }).click()
  await page.getByRole('button', { name: '选择字体一' }).click()
  await expect(page.getByRole('button', { name: '选择字体一' }).getByText('当前在学')).toBeVisible()
  expect(consoleErrors).toEqual([])
})

test('直接打开修改计划页时返回按钮回到首页', async ({ page }) => {
  await page.goto('/#/pages/plan/index')
  await expect(page.getByText('修改计划', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '返回' }).click()
  await expect(page.getByText('今日计划')).toBeVisible()
})

test('可切换多套主题并在刷新后保留选择', async ({ page }) => {
  const pageErrors: string[] = []
  page.on('pageerror', (error) => pageErrors.push(error.message))
  await page.goto('/')
  await page.getByLabel('我').click()
  await expect(page.getByText('主题配色', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '主题配色' }).click()
  await expect(page.getByRole('radio')).toHaveCount(5)

  const blueTheme = page.getByRole('radio', { name: /晴空蓝/ })
  const greenTheme = page.getByRole('radio', { name: /青竹绿/ })
  await greenTheme.click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'jade-green')
  await expect(page.locator('html')).toHaveCSS('--color-primary', '#16856b')
  await expect(greenTheme).toHaveAttribute('aria-checked', 'true')
  await expect(greenTheme.locator('.choice-dot-fill')).toHaveCSS('opacity', '1')
  await expect(blueTheme).toHaveAttribute('aria-checked', 'false')
  await expect(blueTheme.locator('.choice-dot-fill')).toHaveCSS('opacity', '0')

  await page.getByRole('radio', { name: /墨夜/ }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'ink-night')
  await expect(page.locator('html')).toHaveAttribute('data-theme-mode', 'dark')

  await page.getByRole('radio', { name: /新春红/ }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'spring-festival')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'spring-festival')
  await expect(page.getByRole('radio', { name: /新春红/ })).toHaveAttribute('aria-checked', 'true')
  await page.screenshot({ path: 'artifacts/theme-mobile.png', fullPage: true })
  expect(pageErrors).toEqual([])
})

test('我的页面按区块展示菜单并支持滚动', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 720 })
  await page.goto('/#/pages/profile/index')

  await expect(page.getByText('试用17908178540418472')).toBeVisible()
  await expect(page.getByText('累计已学')).toBeVisible()
  await expect(page.getByText('我的学习设备')).toHaveCount(0)
  await expect(page.getByText('我的铜板')).toHaveCount(0)
  await expect(page.locator('.menu-section')).toHaveCount(4)
  await expect(page.getByRole('button', { name: '主题配色' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollHeight > window.innerHeight)).toBe(true)

  const before = await page.evaluate(() => document.scrollingElement?.scrollTop ?? 0)
  await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight))
  await expect(page.getByText('关于我们')).toBeVisible()
  const after = await page.evaluate(() => document.scrollingElement?.scrollTop ?? 0)
  expect(after).toBeGreaterThan(before)
  await expect(page.locator('.bottom-navigation')).toHaveCSS('position', 'fixed')
  const hasStackedNavigationContent = await page.locator('.navigation-content').evaluateAll((items) => (
    items.every((item) => {
      const icon = item.querySelector('.van-icon')
      const label = item.querySelector('.navigation-label')
      if (!icon || !label) return false
      return icon.getBoundingClientRect().bottom <= label.getBoundingClientRect().top
    })
  ))
  expect(hasStackedNavigationContent).toBe(true)
  await page.screenshot({ path: 'artifacts/profile-mobile.png', fullPage: true })
})
