import { expect, test } from '@playwright/test'

test('手机首页只显示指定的学习内容', async ({ page }) => {
  const pageErrors: string[] = []
  page.on('pageerror', (error) => pageErrors.push(error.message))
  await page.goto('/')

  await expect(page.locator('.topbar')).toHaveCSS('padding-top', '30px')
  await expect(page.locator('body')).toHaveCSS('font-size', '12px')
  await expect(page.locator('.font-title').first()).toHaveCSS('font-size', '14px')
  await expect(page.locator('.navigation-item').first()).toHaveCSS('font-size', '7px')
  await expect(page.locator('.font-row').first()).toHaveCSS('min-height', '102px')
  await expect(page.locator('.action-button').first()).toHaveCSS('height', '58px')
  await expect(page.locator('.bottom-navigation')).toHaveCSS('min-height', '72px')
  await expect(page.getByRole('button', { name: '搜索' })).toBeVisible()
  await expect(page.getByRole('button', { name: '消息提示' })).toBeVisible()
  await expect(page.getByRole('button', { name: '主题设置' })).toHaveCount(0)
  await expect(page.locator('.font-title').filter({ hasText: '学习字体：楷体' })).toBeVisible()
  await expect(page.locator('.font-title').filter({ hasText: '对照字体：微软雅黑' })).toBeVisible()
  const learningFontRow = page.locator('.font-row').filter({ hasText: '学习字体：楷体' })
  const referenceFontRow = page.locator('.font-row').filter({ hasText: '对照字体：微软雅黑' })
  await expect(learningFontRow.locator('.cover-name')).toHaveCount(0)
  await expect(learningFontRow.locator('.cover-sample')).toHaveText('永')
  await expect(learningFontRow.locator('.cover-sample')).toHaveCSS('font-family', /KaiTi/)
  await expect(referenceFontRow.locator('.cover-sample')).toHaveText('永')
  await expect(referenceFontRow.locator('.cover-sample')).toHaveCSS('font-family', /Microsoft YaHei/)
  await expect(page.getByText('今日计划')).toBeVisible()
  await expect(page.getByRole('button', { name: '修改' })).toBeVisible()
  await expect(page.getByText('已新学')).toBeVisible()
  await expect(page.getByText('已复习')).toBeVisible()
  await expect(page.getByText('已学习时长')).toBeVisible()
  await expect(page.getByText('x/y')).toHaveCount(2)
  await expect(page.getByText('xxx min')).toBeVisible()
  await expect(page.getByRole('button', { name: '开始学习', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '复习', exact: true })).toBeVisible()
  await expect(page.getByText('功能切换')).toHaveCount(0)
  const navigationItems = page.locator('.navigation-item')
  await expect(navigationItems).toHaveCount(4)
  const hasStackedNavigationContent = await page.locator('.navigation-content').evaluateAll((items) => (
    items.every((item) => {
      const icon = item.querySelector('.van-icon')
      const label = item.querySelector('.navigation-label')
      if (!icon || !label) return false
      return icon.getBoundingClientRect().bottom <= label.getBoundingClientRect().top
    })
  ))
  expect(hasStackedNavigationContent).toBe(true)
  await expect(page.getByText('单字练习')).toBeVisible()
  await expect(page.getByText('对照阅读')).toBeVisible()
  await expect(page.getByText('我', { exact: true })).toBeVisible()
  await expect(page.getByText('今天要做的事')).toHaveCount(0)
  await page.screenshot({ path: 'artifacts/home-mobile.png', fullPage: true })

  await page.getByRole('button', { name: '修改' }).click()
  await expect(page.getByText('修改计划', { exact: true })).toBeVisible()
  await expect(page.getByRole('tab', { name: '修改字体' })).toBeVisible()
  await expect(page.getByText('学习字体：楷体')).toBeVisible()
  await expect(page.getByText('选择学习模式（支持多选）')).toBeVisible()
  await page.getByRole('button', { name: '返回' }).click()
  await expect(page.getByText('今日计划')).toBeVisible()
  await page.getByRole('button', { name: '修改' }).click()
  await expect(page.getByText('修改计划', { exact: true })).toBeVisible()
  await expect(page.locator('.plan-wheel')).toBeVisible()
  await expect(page.locator('.picker-row').first()).toHaveCSS('height', '54px')
  await expect(page.locator('.save-button').first()).toHaveCSS('height', '52px')
  await expect(page.locator('uni-picker-view')).toHaveCount(0)
  await expect(page.locator('uni-radio')).toHaveCount(0)
  const wheel = page.locator('.plan-wheel')
  await expect(wheel).toHaveAttribute('data-selected-count', '15')
  await wheel.hover()
  await page.mouse.wheel(0, 80)
  await expect(wheel).toHaveAttribute('data-selected-count', '20')
  await page.mouse.wheel(0, 10000)
  await expect(wheel).toHaveAttribute('data-selected-count', '100')
  await page.waitForTimeout(300)
  const firstMode = page.locator('.mode-card').filter({ hasText: '查看学习字体选择对照字体' })
  const secondMode = page.locator('.mode-card').filter({ hasText: '查看对照字体选择学习字体' })
  const thirdMode = page.locator('.mode-card').filter({ hasText: '查看学习字体输入对照字体' })
  await expect(thirdMode.locator('.uni-checkbox-input svg')).toHaveCount(1)
  await thirdMode.click()
  await expect(firstMode.locator('.uni-checkbox-input svg')).toHaveCount(1)
  await expect(secondMode.locator('.uni-checkbox-input svg')).toHaveCount(1)
  await expect(thirdMode.locator('.uni-checkbox-input svg')).toHaveCount(0)
  await page.screenshot({ path: 'artifacts/plan-mobile.png', fullPage: true })
  await page.getByRole('button', { name: '保存计划' }).click()
  await expect(page.getByText('今日计划')).toBeVisible()
  expect(pageErrors).toEqual([])
})

test('开始学习前可预览、揭示和交换字体并进入文字详情', async ({ page }) => {
  const pageErrors: string[] = []
  page.on('pageerror', (error) => pageErrors.push(error.message))
  page.on('console', (message) => {
    if (message.type() === 'error') pageErrors.push(message.text())
  })
  await page.goto('/')

  await page.getByRole('button', { name: '开始学习' }).click()
  await expect(page.getByText('今日文字预览', { exact: true })).toHaveCount(0)
  await expect(page.getByText('今日要学 15 个文字')).toBeVisible()
  await expect(page.getByText(/单词/)).toHaveCount(0)
  await expect(page.locator('.character-row')).toHaveCount(15)

  const firstCharacterRow = page.locator('.character-row').first()
  await expect(firstCharacterRow.locator('.character')).toHaveCount(1)
  await firstCharacterRow.getByRole('button', { name: '显示一的微软雅黑字形' }).click()
  await expect(firstCharacterRow.locator('.character')).toHaveCount(2)
  await firstCharacterRow.getByRole('button', { name: '重新遮盖一的微软雅黑字形' }).click()
  await expect(firstCharacterRow.locator('.character')).toHaveCount(1)

  await page.getByRole('button', { name: '交换遮盖字体' }).click()
  await expect(firstCharacterRow.getByRole('button', { name: '显示一的楷体字形' })).toBeVisible()

  await page.getByRole('button', { name: '取消全部遮盖' }).click()
  await expect(firstCharacterRow.locator('.character')).toHaveCount(2)
  await expect(page.getByRole('button', { name: '全部遮盖' })).toBeVisible()
  await page.getByRole('button', { name: '全部遮盖' }).click()
  await expect(firstCharacterRow.getByRole('button', { name: '显示一的楷体字形' })).toBeVisible()
  await page.screenshot({ path: 'artifacts/study-preview-mobile.png', fullPage: true })

  await firstCharacterRow.getByRole('button', { name: '查看一的文字详情' }).click()
  await expect(page.getByText('文字详情', { exact: true })).toHaveCount(0)
  await expect(page.getByLabel('学习字体楷体中的一')).toBeVisible()
  await expect(page.getByLabel('对照字体微软雅黑中的一')).toBeVisible()
  await expect(page.getByRole('button', { name: '搜索' })).toBeVisible()
  await expect(page.getByLabel('收藏当前文字')).toBeVisible()
  await expect(page.getByLabel('斩掉当前文字，后续学习不再出现')).toBeVisible()
  await page.getByLabel('收藏当前文字').click()
  await expect(page.getByLabel('取消收藏当前文字')).toHaveAttribute('aria-pressed', 'true')
  await page.getByLabel('斩掉当前文字，后续学习不再出现').click()
  await expect(page.getByLabel('恢复当前文字到学习列表')).toHaveAttribute('aria-pressed', 'true')
  await page.getByLabel('取消收藏当前文字').click()
  await page.getByLabel('恢复当前文字到学习列表').click()
  await expect(page.getByText('基本释义')).toBeVisible()
  await expect(page.getByText('数词，最小的正整数')).toBeVisible()
  await page.getByRole('button', { name: '搜索' }).click()
  await expect(page.locator('.search-page')).toBeVisible()
  await expect(page.locator('.search-input input')).toBeVisible()
  await page.getByRole('button', { name: '取消搜索' }).click()
  await expect(page.getByText('数词，最小的正整数')).toBeVisible()
  await page.screenshot({ path: 'artifacts/character-detail-mobile.png', fullPage: true })
  await page.getByRole('button', { name: '返回' }).click()
  await expect(page.getByText('今日文字预览', { exact: true })).toHaveCount(0)

  await page.getByRole('button', { name: '开始今日学习' }).click()
  await expect(page.getByText('字形识别', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '搜索' })).toBeVisible()
  await expect(page.getByRole('button', { name: '收藏' })).toBeVisible()
  await expect(page.locator('.topbar-actions').getByRole('button')).toHaveCount(2)
  await expect(page.getByText('今日新学')).toBeVisible()
  await expect(page.getByText('从对照字体中选出同一个字')).toHaveCount(0)
  await expect(page.getByText('看清字形特征，识别它在另一种字体中的写法')).toHaveCount(0)
  await expect(page.locator('.character-option')).toHaveCount(4)
  await expect(page.getByRole('button', { name: '选择文字一' })).toBeVisible()
  const [progressCardBox, promptCardBox] = await Promise.all([
    page.locator('.progress-card').boundingBox(),
    page.locator('.prompt-card').boundingBox(),
  ])
  expect((promptCardBox?.y ?? 0) - ((progressCardBox?.y ?? 0) + (progressCardBox?.height ?? 0))).toBeGreaterThanOrEqual(28)
  await page.screenshot({ path: 'artifacts/study-memory-mobile.png', fullPage: true })

  await page.getByRole('button', { name: '选择文字乙' }).click()
  const wrongOption = page.locator('.character-option.is-wrong')
  await expect(wrongOption).toBeVisible()
  const wrongAnimationName = await wrongOption.evaluate((element) => getComputedStyle(element).animationName)
  expect(wrongAnimationName).toContain('wrong-option-shake')
  const answerError = page.getByText('选择错误，请重新选择')
  await expect(answerError).toBeVisible()
  const [choiceGridBox, answerErrorBox] = await Promise.all([
    page.locator('.choice-grid').boundingBox(),
    answerError.boundingBox(),
  ])
  expect(answerErrorBox?.y ?? 0).toBeGreaterThan((choiceGridBox?.y ?? 0) + (choiceGridBox?.height ?? 0))
  await page.getByRole('button', { name: '选择文字一' }).click()
  await expect(page.getByLabel('文字详情')).toBeVisible()
  await expect(page.getByText('选择错误，请重新选择')).toHaveCount(0)
  await expect(page.getByLabel('学习字体楷体中的一')).toBeVisible()
  await expect(page.getByLabel('对照字体微软雅黑中的一')).toBeVisible()
  await expect(page.getByText('数词，最小的正整数')).toBeVisible()
  await expect(page.getByText('识别正确，继续保持')).toHaveCount(0)
  await expect(page.getByText('1/15')).toBeVisible()

  await page.getByRole('button', { name: '进入下一关' }).click()
  await expect(page.getByText('从学习字体中选出同一个字')).toHaveCount(0)
  await page.getByRole('button', { name: '选择文字乙' }).click()
  await expect(page.getByLabel('文字详情')).toBeVisible()
  await expect(page.getByText('2/15')).toBeVisible()

  await page.getByRole('button', { name: '进入下一关' }).click()
  await expect(page.getByText('文字输入', { exact: true })).toHaveCount(0)
  await expect(page.getByText('输入你看到的文字')).toHaveCount(0)
  await expect(page.getByText(/请用.*输入答案/)).toHaveCount(0)
  await page.screenshot({ path: 'artifacts/study-input-mobile.png', fullPage: true })
  const answerInput = page.locator('.answer-input input')
  await answerInput.fill('十')
  await page.getByRole('button', { name: '确认输入答案' }).click()
  await expect(page.locator('.input-label')).toHaveClass(/is-error/)
  await answerInput.fill('二')
  await expect(page.locator('.input-label')).not.toHaveClass(/is-error/)
  await page.getByRole('button', { name: '确认输入答案' }).click()
  await expect(page.getByLabel('文字详情')).toBeVisible()
  await expect(page.getByText('数词，一加一的和')).toBeVisible()
  await expect(page.getByRole('button', { name: '确认输入答案' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '进入下一关' })).toBeVisible()
  await expect(page.getByText('3/15')).toBeVisible()
  await page.screenshot({ path: 'artifacts/study-character-result-mobile.png', fullPage: true })
  expect(pageErrors).toEqual([])
})

test('搜索支持汉字和拼音匹配、进入文字详情并切换搜索模式', async ({ page }) => {
  const pageErrors: string[] = []
  page.on('pageerror', (error) => pageErrors.push(error.message))
  await page.goto('/')

  await page.getByRole('button', { name: '搜索' }).click()
  const searchInput = page.locator('.search-input input')
  await expect(searchInput).toBeVisible()
  await expect(page.getByRole('searchbox')).toHaveAccessibleName('搜索汉字或拼音')
  await expect(page.getByRole('tab')).toHaveCount(4)
  await expect(page.getByRole('tab', { name: '单字模式' })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('button', { name: /拍照/ })).toHaveCount(0)

  await searchInput.fill('shi')
  await expect(page.locator('.result-item')).not.toHaveCount(0)
  await expect(page.locator('.result-pinyin').filter({ hasText: 'shí' }).first()).toBeVisible()
  await expect(page.locator('.result-scroll')).toBeVisible()
  await page.screenshot({ path: 'artifacts/search-mobile.png', fullPage: true })
  await page.getByRole('button', { name: /^十，shí/ }).click()
  await expect(page.getByText('文字详情', { exact: true })).toHaveCount(0)
  await expect(page.getByText('数词，九加一的和')).toBeVisible()
  await page.getByRole('button', { name: '返回' }).click()
  await expect(searchInput).toHaveValue('shi')

  await searchInput.fill('一')
  const resultScroll = page.locator('.result-scroll')
  const hasScrollableContent = await resultScroll.evaluate((element) => (
    [element, ...element.querySelectorAll('*')].some((candidate) => candidate.scrollHeight > candidate.clientHeight)
  ))
  expect(hasScrollableContent).toBe(true)
  await expect(page.getByRole('button', { name: /^一，yī/ })).toBeVisible()
  await page.getByRole('button', { name: /^一，yī/ }).click()
  await expect(page.getByText('文字详情', { exact: true })).toHaveCount(0)
  await expect(page.getByText('数词，最小的正整数')).toBeVisible()
  await page.getByRole('button', { name: '返回' }).click()
  await expect(searchInput).toHaveValue('一')
  await page.getByRole('tab', { name: '词语模式' }).click()
  await expect(page.getByText('词语模式暂未开放')).toBeVisible()
  await page.getByRole('tab', { name: '单字模式' }).click()
  await searchInput.press('Enter')
  await page.getByRole('button', { name: '清空搜索' }).click()
  await expect(page.getByText('搜索记录', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '搜索 一' })).toBeVisible()
  expect(pageErrors).toEqual([])
})

test('字体管理可浏览、添加并切换字体', async ({ page }) => {
  const consoleErrors: string[] = []
  page.on('pageerror', (error) => consoleErrors.push(error.message))
  page.on('console', (message) => {
    if (message.type() === 'error') consoleErrors.push(message.text())
  })
  await page.goto('/#/pages/plan/index')

  const saveButtonWidth = await page.getByRole('button', { name: '保存计划' }).evaluate((element) => element.getBoundingClientRect().width)
  await page.getByRole('tab', { name: '修改字体' }).click()
  await expect(page.locator('.font-card-title').filter({ hasText: '楷体' })).toBeVisible()
  await expect(page.locator('.font-card-title').filter({ hasText: '微软雅黑' })).toBeVisible()
  await expect(page.getByText('当前在学')).toBeVisible()
  await expect(page.getByRole('button', { name: '添加字体' })).toBeVisible()
  await expect(page.locator('.add-font-footer')).toHaveCSS('position', 'fixed')
  await expect(page.getByRole('button', { name: '添加字体' })).toHaveCSS('background-color', 'rgb(23, 85, 233)')
  await expect(page.getByRole('button', { name: '添加字体' })).toHaveCSS('border-bottom-left-radius', '8px')
  await expect(page.getByRole('button', { name: '添加字体' })).toHaveCSS('border-bottom-right-radius', '8px')
  expect(await page.getByRole('button', { name: '添加字体' }).evaluate((element) => element.getBoundingClientRect().width)).toBe(saveButtonWidth)
  await expect(page.locator('.managed-font-list')).toHaveCSS('overflow-y', 'auto')
  await expect(page.getByText('徽章', { exact: true })).toHaveCount(0)
  await page.screenshot({ path: 'artifacts/fonts-mobile.png', fullPage: true })

  await page.getByRole('button', { name: '添加字体' }).click()
  await expect(page.getByText('选择字体', { exact: true })).toHaveCount(0)
  await expect(page.getByText('选择练习字体')).toBeVisible()
  await expect(page.getByText(/添加后可在“修改字体”中切换/)).toBeVisible()
  await expect(page.locator('.catalog-item')).toHaveCount(5)
  await expect(page.locator('.catalog-page')).toHaveCSS('overflow-y', 'auto')
  expect(await page.locator('.catalog-page').evaluate((element) => element.scrollHeight > element.clientHeight)).toBe(true)
  const regularScript = page.getByRole('button', { name: '添加楷书' })
  await expect(regularScript.locator('.font-name')).toHaveText('楷书')
  await expect(regularScript.getByText('横平竖直、法度严谨，适合认识汉字的基本结构。')).toBeVisible()
  await expect(regularScript.locator('.cover-sample')).toHaveText('楷')
  await regularScript.click()
  await expect(page.getByRole('button', { name: '楷书已添加' })).toBeVisible()
  await page.screenshot({ path: 'artifacts/font-catalog-mobile.png', fullPage: true })
  await page.getByRole('button', { name: '返回' }).click()
  await expect(page.getByRole('button', { name: '选择楷书' })).toBeVisible()

  await page.getByRole('button', { name: '选择楷书' }).click()
  await expect(page.getByRole('button', { name: '选择楷书' }).getByText('当前在学')).toBeVisible()
  await page.getByRole('tab', { name: '修改计划' }).click()
  await expect(page.getByText('学习字体：楷书')).toBeVisible()
  await page.getByRole('button', { name: '返回' }).click()
  await expect(page.locator('.font-title').filter({ hasText: '学习字体：楷书' })).toBeVisible()
  await page.getByRole('button', { name: '开始学习', exact: true }).click()
  await expect(page.getByText('今日文字预览', { exact: true })).toHaveCount(0)
  await expect(page.getByText('楷书', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '开始今日学习' }).click()
  await expect(page.locator('.prompt-card')).toHaveAttribute('aria-label', '题目使用楷书展示，一')
  expect(consoleErrors).toEqual([])
})

test('直接打开修改计划页时返回按钮回到首页', async ({ page }) => {
  await page.goto('/#/pages/plan/index')
  await expect(page.getByText('修改计划', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '返回' }).click()
  await expect(page.getByText('今日计划')).toBeVisible()
})

test('可切换多套主题并在刷新后保留选择', async ({ page }) => {
  const pageErrors: string[] = []
  page.on('pageerror', (error) => pageErrors.push(error.message))
  await page.goto('/')
  await page.getByLabel('我').click()
  await expect(page.getByText('主题配色', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '主题配色' }).click()
  await expect(page.getByRole('radio')).toHaveCount(5)

  const blueTheme = page.getByRole('radio', { name: /晴空蓝/ })
  const greenTheme = page.getByRole('radio', { name: /青竹绿/ })
  await greenTheme.click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'jade-green')
  await expect(page.locator('html')).toHaveCSS('--color-primary', '#16856b')
  await expect(greenTheme).toHaveAttribute('aria-checked', 'true')
  await expect(greenTheme.locator('.choice-dot-fill')).toHaveCSS('opacity', '1')
  await expect(blueTheme).toHaveAttribute('aria-checked', 'false')
  await expect(blueTheme.locator('.choice-dot-fill')).toHaveCSS('opacity', '0')

  await page.getByRole('radio', { name: /墨夜/ }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'ink-night')
  await expect(page.locator('html')).toHaveAttribute('data-theme-mode', 'dark')

  await page.getByRole('radio', { name: /新春红/ }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'spring-festival')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'spring-festival')
  await expect(page.getByRole('radio', { name: /新春红/ })).toHaveAttribute('aria-checked', 'true')
  await page.screenshot({ path: 'artifacts/theme-mobile.png', fullPage: true })
  expect(pageErrors).toEqual([])
})

test('我的页面按区块展示菜单并支持滚动', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 720 })
  await page.goto('/#/pages/profile/index')

  await expect(page.getByText('试用17908178540418472')).toBeVisible()
  await expect(page.getByText('累计已学')).toBeVisible()
  await expect(page.getByText('我的学习设备')).toHaveCount(0)
  await expect(page.getByText('我的铜板')).toHaveCount(0)
  await expect(page.locator('.menu-section')).toHaveCount(4)
  await expect(page.locator('.menu-item').first()).toHaveCSS('min-height', '58px')
  await expect(page.getByRole('button', { name: '主题配色' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollHeight > window.innerHeight)).toBe(true)

  const before = await page.evaluate(() => document.scrollingElement?.scrollTop ?? 0)
  await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight))
  await expect(page.getByText('关于我们')).toBeVisible()
  const after = await page.evaluate(() => document.scrollingElement?.scrollTop ?? 0)
  expect(after).toBeGreaterThan(before)
  await expect(page.locator('.bottom-navigation')).toHaveCSS('position', 'fixed')
  const hasStackedNavigationContent = await page.locator('.navigation-content').evaluateAll((items) => (
    items.every((item) => {
      const icon = item.querySelector('.van-icon')
      const label = item.querySelector('.navigation-label')
      if (!icon || !label) return false
      return icon.getBoundingClientRect().bottom <= label.getBoundingClientRect().top
    })
  ))
  expect(hasStackedNavigationContent).toBe(true)
  await page.screenshot({ path: 'artifacts/profile-mobile.png', fullPage: true })
})

test('个人设置齿轮打开设置页并沿用主题配色', async ({ page }) => {
  const pageErrors: string[] = []
  page.on('pageerror', (error) => pageErrors.push(error.message))
  await page.goto('/#/pages/profile/index')

  await page.getByRole('button', { name: '个人设置' }).click()
  await expect(page.getByText('设置', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '账号管理' })).toBeVisible()
  await expect(page.getByRole('button', { name: '显示设置' })).toBeVisible()
  await expect(page.getByRole('switch', { name: '长辈版' })).toHaveAttribute('aria-checked', 'false')
  await expect(page.getByRole('button', { name: '退出登录' })).toBeVisible()
  await expect(page.locator('.setting-row').first()).toHaveCSS('min-height', '70px')

  await page.getByRole('switch', { name: '长辈版' }).click()
  await expect(page.getByRole('switch', { name: '长辈版' })).toHaveAttribute('aria-checked', 'true')
  await page.reload()
  await expect(page.getByRole('switch', { name: '长辈版' })).toHaveAttribute('aria-checked', 'true')

  await page.getByRole('button', { name: '显示设置' }).click()
  await expect(page.getByText('主题设置', { exact: true })).toHaveCount(0)
  await page.getByRole('radio', { name: /青竹绿/ }).click()
  await page.getByRole('button', { name: '返回' }).click()
  await expect(page.getByText('设置', { exact: true })).toHaveCount(0)
  await expect(page.locator('.settings-page')).toHaveCSS('color', 'rgb(32, 52, 46)')

  await page.screenshot({ path: 'artifacts/settings-mobile.png', fullPage: true })
  expect(pageErrors).toEqual([])
})

test('个人资料可编辑并在刷新后保留', async ({ page }) => {
  const pageErrors: string[] = []
  page.on('pageerror', (error) => pageErrors.push(error.message))
  page.on('console', (message) => {
    if (message.type() === 'error') pageErrors.push(message.text())
  })
  await page.goto('/#/pages/profile/index')

  await page.getByRole('button', { name: '查看个人资料' }).click()
  await expect(page.getByText('个人资料', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '编辑头像' })).toBeVisible()
  await expect(page.getByRole('button', { name: '编辑昵称' })).toContainText('试用17908178540418472')
  await expect(page.getByRole('button', { name: '编辑性别' })).toContainText('保密')
  await expect(page.getByRole('button', { name: '编辑出生' })).toContainText('未填写')
  await expect(page.getByRole('button', { name: '编辑位置' })).toContainText('未填写')
  await expect(page.getByText('学校', { exact: true })).toHaveCount(0)
  await expect(page.getByText('年级', { exact: true })).toHaveCount(0)
  await expect(page.getByText('福建', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: '编辑昵称' }).click()
  await expect(page.getByText('修改昵称', { exact: true })).toBeVisible()
  const nicknameInput = page.getByRole('textbox', { name: '昵称' })
  await nicknameInput.fill('林同学')
  await expect(nicknameInput).toHaveText('林同学')
  await page.getByRole('button', { name: '保存昵称' }).click()
  await expect(page.getByText('修改昵称', { exact: true })).toBeHidden()
  await expect(page.getByRole('button', { name: '编辑昵称' })).toContainText('林同学')

  await page.getByRole('button', { name: '编辑性别' }).click()
  await expect(page.getByText('选择性别', { exact: true })).toBeVisible()
  await page.getByRole('radio', { name: '女' }).click()
  await expect(page.getByRole('button', { name: '编辑性别' })).toContainText('女')

  await page.getByRole('button', { name: '编辑出生' }).click()
  await expect(page.getByText('选择出生日期', { exact: true })).toBeVisible()
  await expect(page.locator('.wheel-column')).toHaveCount(3)
  await page.getByRole('button', { name: '确认出生日期' }).click()
  await expect(page.getByRole('button', { name: '编辑出生' })).toContainText('2000.01.01')

  await page.getByRole('button', { name: '编辑位置' }).click()
  await expect(page.getByText('选择地区', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '选择福建省' }).click()
  await page.getByRole('button', { name: '选择福州市' }).click()
  await page.getByRole('button', { name: '确定鼓楼区' }).click()
  await expect(page.getByRole('button', { name: '编辑位置' })).toContainText('福建省 福州市 鼓楼区')

  await page.reload()
  await expect(page.getByRole('button', { name: '编辑昵称' })).toContainText('林同学')
  await expect(page.getByRole('button', { name: '编辑性别' })).toContainText('女')
  await expect(page.getByRole('button', { name: '编辑出生' })).toContainText('2000.01.01')
  await expect(page.getByRole('button', { name: '编辑位置' })).toContainText('福建省 福州市 鼓楼区')

  await page.goto('/#/pages/theme/index')
  await page.getByRole('radio', { name: /墨夜/ }).click()
  await page.goto('/#/pages/personal-profile/index')
  await expect(page.locator('.personal-profile-page')).toHaveCSS('color', 'rgb(241, 244, 250)')
  await expect(page.locator('.personal-profile-page')).toHaveCSS('background-color', 'rgb(27, 33, 44)')

  await page.screenshot({ path: 'artifacts/personal-profile-mobile.png', fullPage: true })
  expect(pageErrors).toEqual([])
})
